{
 "title": "RZSpinnakerDashboard",
 "description": "Metrics RZ cares about https://blog.spinnaker.io/monitoring-spinnaker-part-1-4847f42a3abd",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Function", "query": "delta,rate,idelta,irate" },
   { "name": "SamplePeriod", "query": "1m,5m,10m,15m,30m,1h" },
   {
    "name": "Application",
    "query": "label_values(orca:stage:invocations_total,application)"
   }
  ]
 },
 "panels": [
  {
   "title": "ActiveStagesbyApplication(orca,$Application)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum($Function(orca:stage:invocations_total{application=~\"$Application\"}[$SamplePeriod]))by(application,type)",
     "legendFormat": "{{application}}/{{type}}"
    }
   ]
  },
  {
   "title": "OrcaQueueDepth",
   "type": "graph",
   "description": "Spinnaker Orca queue depth. Ready queue should always be 0 or close to it. If not, scale Orca. I like this graph, especially when it looks like this. Keiko supports setting a delivery time for messages, so you’ll always see queued messages out pacing in-process messages if your Spinnaker install is active. Things like wait tasks, execution windows, retries, and so-on all schedule message delivery in the future, and in-process messages are usually in-process for a handful of milliseconds. Operating Orca, one of your life mission is to keep ready messages at 0. A ready message is a message that has a delivery time of now or in the past, but it hasn’t been picked up and transitioned into processing yet: This is a key contributor to a complaint of,'Spinnaker is slow.' As I’ve mentioned before, Orca is horizontally scalable. Give Orca an adrenaline shot of instances if you see ready messages over 0 for more than two intervals so you can clear the queue out.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "orca:queue:unacked:depth", "legendFormat": "unacked({{pod}})" },
    { "expr": "orca:queue:ready:depth", "legendFormat": "ready({{pod}})" },
    { "expr": "orca:queue:depth", "legendFormat": "depth({{pod}})" }
   ]
  },
  {
   "title": "MessageLag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(orca:queue:message:lag__totalTime_total/orca:queue:message:lag__count_total)"
    }
   ]
  },
  {
   "title": "OrcaRunningTasksTotalDurationbyApp",
   "type": "graph",
   "description": "Spinnaker Orca tasks currently running grouped by application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(orca:task:invocations:duration__count_total{status=\"RUNNING\",cloudProvider=\"kubernetes\"})by(application,executionType)",
     "legendFormat": "{{application}}{{executionType}}"
    }
   ]
  },
  {
   "title": "ActiveOrcaExecutions",
   "type": "graph",
   "description": "This is really just good insight for answering the question of workload distribution. Since adding this metric, we’ve never seen it crater, but if that were to happen it’d be bad. For Netflix, most ORCHESTRATION executions are API clients. Disregarding what the execution is doing, there’s no baseline cost difference between a running orchestration and a pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(orca:executions:active{})by(executionType)",
     "legendFormat": "{{executionType}}"
    }
   ]
  },
  {
   "title": "Retried,Dead,&OrphanedSpinQueue",
   "type": "graph",
   "description": "It sounds worse than it is. Retried is a normal error condition by itself. Dead-lettered occurs when a message has been retried a bunch of times and has never been successfully delivered. A dead message gets dropped into its own sorted set in Redis which, if you want, can be redriven with some Redis-fu, but there’s no current tooling around that. We know we need better tooling around dead messages — but we typically do not redrive messages. Orphaned messages are bad. They’re messages whose message contents are in the queue, but do not have a pointer in either the queue set or unacked set. This is a sign of an internal error, likely a troubling issue with Redis. It “should never happen” if your system is healthy, and likewise “should never happen” even if your system is really, really overloaded. It’s worth a bugreport.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "orca:queue:retried:messages_total",
     "legendFormat": "retried({{pod}})"
    },
    { "expr": "orca:queue:dead:messages_total", "legendFormat": "dead({{pod}})" },
    { "expr": "orca:queue:orphaned:messages", "legendFormat": "orphaned({{pod}})" }
   ]
  }
 ]
}